//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Activity_Time { get; set; }
        public string Activity_Title { get; set; }
        public string Activity_Url { get; set; }
        public Nullable<int> Activity_State { get; set; }
    }
}
