//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditing_Blog
    {
        public int Auditing_Blog_Id { get; set; }
        public Nullable<int> AdminUser_Id { get; set; }
        public Nullable<int> Write_blog_Id { get; set; }
        public Nullable<int> Auditing_Blog_State { get; set; }
        public Nullable<System.DateTime> Auditing_Blog_Time { get; set; }
        public string Auditing_Blog_Msg { get; set; }
    }
}
