//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog_Recommend
    {
        public int id { get; set; }
        public string Blog_Title { get; set; }
        public string Write_blog_Id { get; set; }
        public string Blog_Type { get; set; }
        public string Blog_Author { get; set; }
        public Nullable<System.DateTime> Blog_Time { get; set; }
        public Nullable<int> Blog_ReadNum { get; set; }
        public string Blog_Message { get; set; }
    }
}
