//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_Id { get; set; }
        public Nullable<int> Comment_User { get; set; }
        public Nullable<System.DateTime> Comment_Time { get; set; }
        public Nullable<int> Write_blog_Id { get; set; }
        public string Comment_Content { get; set; }
        public Nullable<int> ULogin_Id { get; set; }
        public Nullable<int> Parent_Comment_Id { get; set; }
    }
}
