//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configure
    {
        public int Configure_Id { get; set; }
        public Nullable<int> ULogin_Id { get; set; }
        public string Configure_Title { get; set; }
        public string Configure_Dscribe { get; set; }
        public Nullable<int> Configure_Skin { get; set; }
        public Nullable<int> Configure_Editor { get; set; }
        public Nullable<int> Configure_Notice { get; set; }
        public Nullable<int> Configure_Cpyright { get; set; }
    }
}
