//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details
    {
        public int Details_Id { get; set; }
        public string Details_Text { get; set; }
        public string Details_PageView { get; set; }
        public Nullable<int> Details_ThumbUp { get; set; }
        public Nullable<int> Details_Collection { get; set; }
        public string Details_Comment { get; set; }
        public string Details_Time { get; set; }
        public Nullable<int> Details_Original { get; set; }
        public Nullable<int> ULogin_Id { get; set; }
    }
}
