//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUser
    {
        public int FollowUser_ID { get; set; }
        public Nullable<int> FollowUser_User1 { get; set; }
        public Nullable<int> FollowUser_User2 { get; set; }
        public string FollowUser_Remark { get; set; }
        public Nullable<System.DateTime> FollowUser_FollowDate { get; set; }
        public Nullable<System.DateTime> FollowUser_CancelData { get; set; }
    }
}
