//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gold_Score_Notes
    {
        public int Gold_Score_Notes_Id { get; set; }
        public Nullable<int> Gold_Score_Notes_UseType { get; set; }
        public Nullable<int> Gold_Score_Notes_Type { get; set; }
        public Nullable<System.DateTime> Gold_Score_Notes_Time { get; set; }
    }
}
