//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gold_Return
    {
        public int Gold_Return_Id { get; set; }
        public Nullable<int> Gold_Return_Max { get; set; }
        public Nullable<int> Gold_Return_Min { get; set; }
        public Nullable<int> Gold_Return_Retutn { get; set; }
    }
}
