//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULogin
    {
        public int ULogin_Id { get; set; }
        public string ULogin_Phone { get; set; }
        public string ULogin_Email { get; set; }
        public string ULogin_Password { get; set; }
        public string Ulogin_BlogName { get; set; }
        public Nullable<int> Users_Details_ID { get; set; }
    }
}
