//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Details
    {
        public int Users_Details_ID { get; set; }
        public string Users_Details_Name { get; set; }
        public string Users_Details_RealName { get; set; }
        public string Users_Details_Jop { get; set; }
        public Nullable<int> Users_Details_Sex { get; set; }
        public string Users_Details_Photo { get; set; }
        public string Users_Details_Birthday { get; set; }
        public string Users_Details_Industry { get; set; }
        public Nullable<System.DateTime> Users_Details_LoginDate { get; set; }
        public string Users_Details_LoginUrl { get; set; }
        public Nullable<int> Users_Details_Integral { get; set; }
        public Nullable<int> Users_Details_Gold { get; set; }
        public string Users_Details_Resume { get; set; }
    }
}
